In [2]:
pip install numpy pandas

Requirement already satisfied: numpy in c:\users\india\appdata\local\programs\python\python312\lib\site-packages (1.26.3)
Requirement already satisfied: pandas in c:\users\india\appdata\local\programs\python\python312\lib\site-packages (2.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\india\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\india\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\india\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2023.4)
Requirement already satisfied: six>=1.5 in c:\users\india\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd
import numpy as np

file_path = "VEXAR_Fleet_Dataset_CANDIDATE_VERSION (2).xlsx"

drivers = pd.read_excel(
    file_path,
    sheet_name="Drivers",
    header=1
)

vehicles = pd.read_excel(
    file_path,
    sheet_name="Vehicles",
    header=1
)

trips = pd.read_excel(
    file_path,
    sheet_name="Trips",
    header=1
)

telemetry = pd.read_excel(
    file_path,
    sheet_name="Telemetry",
    header=1
)

In [5]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
def fix_headers(df):
    df.columns = df.iloc[0]
    df = df.iloc[1:].reset_index(drop=True)
    return df

drivers = fix_headers(drivers)
vehicles = fix_headers(vehicles)
trips = fix_headers(trips)
telemetry = fix_headers(telemetry)

In [8]:
print(drivers.shape)
print(vehicles.shape)
print(trips.shape)
print(telemetry.shape)

(30, 8)
(30, 8)
(450, 14)
(12987, 13)

In [9]:
print("DRIVERS")
print(drivers.columns.tolist())

print("\nVEHICLES")
print(vehicles.columns.tolist())

print("\nTRIPS")
print(trips.columns.tolist())

print("\nTELEMETRY")
print(telemetry.columns.tolist())

DRIVERS
['Driver_ID', 'Driver_Name', 'Age', 'Gender', 'License_Experience_Years', 'Date_Joined_Fleet', 'Primary_Vehicle_ID', 'Home_Hub']

VEHICLES
['Vehicle_ID', 'Vehicle_Type', 'Make', 'Model', 'Manufacture_Year', 'Registration_Date', 'Odometer_KM_Start_of_Week', 'Last_Service_Date']

TRIPS
['Trip_ID', 'Driver_ID', 'Vehicle_ID', 'Trip_Date', 'Start_Time', 'End_Time', 'Duration_Min', 'Distance_KM', 'Avg_Speed_kmph', 'Max_Speed_kmph', 'Start_Latitude', 'Start_Longitude', 'End_Latitude', 'End_Longitude']

TELEMETRY
['Trip_ID', 'Driver_ID', 'Vehicle_ID', 'Timestamp', 'Latitude', 'Longitude', 'Speed_kmph', 'Accel_X_g', 'Accel_Y_g', 'Accel_Z_g', 'Gyro_X_dps', 'Gyro_Y_dps', 'Gyro_Z_dps']

In [10]:
trips.groupby("Driver_ID")["Trip_ID"].count()

Driver_ID
D01    15
D02    15
D03    15
D04    15
D05    15
D06    15
D07    15
D08    15
D09    15
D10    15
D11    15
D12    15
D13    15
D14    15
D15    15
D16    15
D17    15
D18    15
D19    15
D20    15
D21    15
D22    15
D23    15
D24    15
D25    15
D26    15
D27    15
D28    15
D29    15
D30    15
Name: Trip_ID, dtype: int64

In [11]:
print("Trips:", trips["Trip_ID"].nunique())
print("Telemetry trips:", telemetry["Trip_ID"].nunique())

Trips: 450
Telemetry trips: 450

In [12]:
print("DRIVERS")
print(drivers.isnull().sum())

print("\nVEHICLES")
print(vehicles.isnull().sum())

print("\nTRIPS")
print(trips.isnull().sum())

print("\nTELEMETRY")
print(telemetry.isnull().sum())

DRIVERS
0
Driver_ID                   0
Driver_Name                 0
Age                         0
Gender                      0
License_Experience_Years    0
Date_Joined_Fleet           0
Primary_Vehicle_ID          0
Home_Hub                    0
dtype: int64

VEHICLES
0
Vehicle_ID                   0
Vehicle_Type                 0
Make                         0
Model                        0
Manufacture_Year             0
Registration_Date            0
Odometer_KM_Start_of_Week    0
Last_Service_Date            0
dtype: int64

TRIPS
0
Trip_ID            0
Driver_ID          0
Vehicle_ID         0
Trip_Date          0
Start_Time         0
End_Time           0
Duration_Min       0
Distance_KM        0
Avg_Speed_kmph     0
Max_Speed_kmph     0
Start_Latitude     0
Start_Longitude    0
End_Latitude       0
End_Longitude      0
dtype: int64

TELEMETRY
0
Trip_ID       0
Driver_ID     0
Vehicle_ID    0
Timestamp     0
Latitude      0
Longitude     0
Speed_kmph    0
Accel_X_g     0
Accel_Y_g     0
Accel_Z_g     0
Gyro_X_dps    0
Gyro_Y_dps    0
Gyro_Z_dps    0
dtype: int64

In [13]:
print("Driver duplicate rows:",
      drivers.duplicated().sum())

print("Vehicle duplicate rows:",
      vehicles.duplicated().sum())

print("Trip duplicate rows:",
      trips.duplicated().sum())

print("Telemetry duplicate rows:",
      telemetry.duplicated().sum())

Driver duplicate rows: 0
Vehicle duplicate rows: 0
Trip duplicate rows: 0
Telemetry duplicate rows: 0

In [14]:
invalid_trip_ids = telemetry[
    ~telemetry["Trip_ID"].isin(trips["Trip_ID"])
]

print(len(invalid_trip_ids))

0

In [15]:
driver_numeric = [
    "Age",
    "License_Experience_Years"
]

vehicle_numeric = [
    "Manufacture_Year",
    "Odometer_KM_Start_of_Week"
]

trip_numeric = [
    "Duration_Min",
    "Distance_KM",
    "Avg_Speed_kmph",
    "Max_Speed_kmph",
    "Start_Latitude",
    "Start_Longitude",
    "End_Latitude",
    "End_Longitude"
]

telemetry_numeric = [
    "Latitude",
    "Longitude",
    "Speed_kmph",
    "Accel_X_g",
    "Accel_Y_g",
    "Accel_Z_g",
    "Gyro_X_dps",
    "Gyro_Y_dps",
    "Gyro_Z_dps"
]

In [17]:
drivers["Date_Joined_Fleet"] = pd.to_datetime(
    drivers["Date_Joined_Fleet"],
    errors="coerce"
)

In [18]:
vehicles["Registration_Date"] = pd.to_datetime(
    vehicles["Registration_Date"],
    errors="coerce"
)

vehicles["Last_Service_Date"] = pd.to_datetime(
    vehicles["Last_Service_Date"],
    errors="coerce"
)

In [20]:
trips["Trip_Date"] = pd.to_datetime(
    trips["Trip_Date"],
    errors="coerce"
)

In [21]:
trips["Start_DateTime"] = pd.to_datetime(
    trips["Trip_Date"].dt.strftime("%Y-%m-%d") + " " +
    trips["Start_Time"].astype(str)
)

trips["End_DateTime"] = pd.to_datetime(
    trips["Trip_Date"].dt.strftime("%Y-%m-%d") + " " +
    trips["End_Time"].astype(str)
)

In [22]:
telemetry["Timestamp"] = pd.to_datetime(
    telemetry["Timestamp"],
    errors="coerce"
)

In [23]:
telemetry["Timestamp"].isna().sum()

0

In [24]:
telemetry[
    [
        "Speed_kmph",
        "Accel_X_g",
        "Accel_Y_g",
        "Accel_Z_g",
        "Gyro_X_dps",
        "Gyro_Y_dps",
        "Gyro_Z_dps"
    ]
].describe().T

              count  unique    top   freq
0
Speed_kmph  12987.0   599.0  0.000  188.0
Accel_X_g   12987.0   943.0 -0.005  104.0
Accel_Y_g   12987.0   695.0 -0.015  115.0
Accel_Z_g   12987.0   426.0  1.006  158.0
Gyro_X_dps  12987.0  1184.0 -0.440   38.0
Gyro_Y_dps  12987.0  1175.0 -0.070   37.0
Gyro_Z_dps  12987.0  1562.0  0.370   37.0

In [25]:
telemetry[
    ["Latitude", "Longitude"]
].describe().T

             count   unique        top  freq
0
Latitude   12987.0  12466.0  12.888484   4.0
Longitude  12987.0  12450.0  77.618664   3.0

In [26]:
telemetry["Speed_kmph"].describe()

count     12987
unique      599
top           0
freq        188
Name: Speed_kmph, dtype: int64

In [27]:
telemetry["Speed_kmph"].value_counts().head(20)

Speed_kmph
0       188
25.6     67
27.1     63
26.9     62
25.9     62
21.7     62
28.2     62
32.6     61
31.7     61
24.9     61
24.2     61
25       59
21.3     58
21.5     58
28.6     58
21       57
25.5     57
24.6     56
26.4     56
30       56
Name: count, dtype: int64

In [28]:
(telemetry["Speed_kmph"] == 0).sum()

188

In [29]:
telemetry = telemetry.sort_values(
    ["Trip_ID", "Timestamp"]
).reset_index(drop=True)

In [30]:
telemetry["Time_Diff_Min"] = (
    telemetry.groupby("Trip_ID")["Timestamp"]
    .diff()
    .dt.total_seconds() / 60
)

In [31]:
telemetry["Time_Diff_Min"].describe()

count    12537.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
Name: Time_Diff_Min, dtype: float64

In [32]:
telemetry["Time_Diff_Min"].value_counts().sort_index().head(20)

Time_Diff_Min
1.0    12537
Name: count, dtype: int64

In [33]:
telemetry[
    telemetry["Time_Diff_Min"] > 1.5
].shape

(0, 14)

In [34]:
telemetry_counts = (
    telemetry.groupby("Trip_ID")
    .size()
    .reset_index(name="Telemetry_Count")
)

trip_check = trips.merge(
    telemetry_counts,
    on="Trip_ID",
    how="left"
)

trip_check[
    ["Trip_ID", "Duration_Min", "Telemetry_Count"]
].head(10)

  Trip_ID Duration_Min  Telemetry_Count
0  T00001           16               16
1  T00002           22               22
2  T00003           27               27
3  T00004           42               42
4  T00005           13               13
5  T00006           19               19
6  T00007           15               15
7  T00008           41               41
8  T00009           31               31
9  T00010           33               33

In [35]:
drivers_clean = drivers.copy()
vehicles_clean = vehicles.copy()
trips_clean = trips.copy()
telemetry_clean = telemetry.copy()

In [36]:
telemetry_clean = telemetry_clean.drop(
    columns=["Time_Diff_Min"],
    errors="ignore"
)

In [38]:
drivers_clean.to_csv(
    "Preprocessed_Data/drivers_clean.csv",
    index=False
)

vehicles_clean.to_csv(
    "Preprocessed_Data/vehicles_clean.csv",
    index=False
)

trips_clean.to_csv(
    "Preprocessed_Data/trips_clean.csv",
    index=False
)

telemetry_clean.to_csv(
    "Preprocessed_Data/telemetry_clean.csv",
    index=False
)